### ISSUE TITLE
I cannot match the H2's colour

### ISSUE THREAD

**Issue by Sam-Le68** [Sam-Le68/arrrgenes-treasure-tours#1]
![Screen Shot 2020-04-08 at 5 32 41 AM](https://user-images.githubusercontent.com/55094125/78725690-5f3be600-795a-11ea-8598-ea6e4dedafb8.png)

Hi, I ran into this problem. I download Colour Oracle to test it but it seemed fine, I do not know what my mistake is. Pls help. 

@muxlowc 
@mackenzierose

**Comment by muxlowc** [comment]
@Sam-Le68 

Try adding: 

1) outline-color: #fff; to your .btn-banner:hover, .btn-banner:focus – this will make your focus outline be a higher contrast on your dark brown background)

2) background-color: #704c2a; to your .banner – this will make sure that your banner background is a dark brown even if your background-image breaks/doesn't load (or else you'll have white text on a white background)

Hope that helps!

**Comment by Sam-Le68** [comment]
I fixed it nicely, thank you.
